---
title: "darkend_reevaluated_analyses"
output: html_document
date: '2023-04-21'
---


```{r, include=FALSE}
library(lme4)
library(lmerTest)
library(dplyr)
library(sjPlot)
```


## DATA
```{r}
data = read.csv('2.2._rvals_per_reevaluated_episode_include_subcortical.csv')

dim(data)
```



### setting up the data frames
```{r}
data$label <- as.factor(data$label)
reevaluated_control <- c(-1,1)  
#want greater distance for reevaluated as opposed to null
contrasts(data$label) <- cbind(reevaluated_control)

contrasts(data$label) 
```





# START HERE:
# "episode" is dummy-coded with 5 levels and needed to create the episode pairings to then use them as a random effect
```{r}
# dummy code

data <- data %>%
  mutate(episode_label = case_when(
    episode %in% c(1, 2) ~ "1_2",
    episode %in% c(3, 4) ~ "3_4",
    episode %in% c(5, 6) ~ "5_6",
    episode %in% c(7, 8) ~ "7_8",
    episode %in% c(9, 10) ~ "9_10",
    TRUE ~ as.character(episode)  
  ))

#then want to use this as a random effect 
#whole brain model
model3 <- lmer(1-r~label + (1|sub) + (1|episode_label) + (1|node), data = data)
tab_model(model3)

```


## Do it per node:
```{r}
unique_subjects <- unique(data$sub)
unique_nodes <- unique(data$node)
result_df <- data.frame(sub = character(), node = numeric(), estimate = numeric(), p = numeric())

for (node in unique_nodes) {
  print(node)
    
    subset_data <- data[data$node == node, ]
    subset_data$label <- as.factor(subset_data$label)
    reevaluated_control <- c(-1,1)  #setting up the contrast in the expected direction
    contrasts(subset_data$label) <- cbind(reevaluated_control)


    # Fit the mixed-effects model
    model3 <- lmer(1-r~label + (1|sub) + (1|episode_label), data = subset_data)

    # Get the model summary
    model_summary <- summary(model3)
    
    # Extract the estimate and p-value 
    estimate <- model_summary$coefficients["labelreevaluated_control", "Estimate"]
    p_value <- model_summary$coefficients["labelreevaluated_control", "Pr(>|t|)"]
    
    result_df <- rbind(result_df, data.frame(node = node, estimate = estimate, p = p_value))
  }

result_df

output_folder <- "model_outputs"

if (!file.exists(output_folder)) {
  dir.create(output_folder)
}

output_file <- file.path(output_folder, "lmer_across_node_estimate_reevaluated_episode_by_GLM_episodelabel_as_random_effect_include_subcortical.csv")

write.csv(result_df, file = output_file, row.names = FALSE)

```

