---
title: "1.3_prepost_lmer_model"
output: html_document
date: '2023-04-21'
---


```{r, include=FALSE}
library(lme4)       
library(lmerTest)   
library(dplyr)      
library(sjPlot)     

```


## DATA
```{r}

current_directory <- getwd()
print(current_directory) 

file_path <- paste(current_directory, '1.2._pre_post_for_LME_all_subcortical_new.csv', sep = "/")
data = read.csv(file_path)

dim(data)
```



### setting up the data frames
```{r}
data$label <- as.factor(data$label)
condpost_pre <- c(-1,1)   #will set up the model as a distance 
#expecting greater distance in the pre-twist period
contrasts(data$label) <- cbind(condpost_pre)

```


### ALL NODE MODEL!!!
```{r}
#doing 1-r since it is a distance! 
m <- lmer(1-r~label + (1|sub) + (1|node) , data=data)
tab_model(m) 

```


## Do it per node:
```{r}
# Initialize a counter for nodes with singularity errors (if any!)
singularity_count <- 0
singular_nodes <- c()  

unique_subjects <- unique(data$sub)
unique_nodes <- unique(data$node)
result_df <- data.frame(sub = character(), node = numeric(), estimate = numeric(), p = numeric())

for (node in unique_nodes) {
  
  print(node)
  
  # Filter the data for the current node
  subset_data <- data[data$node == node, ]
  subset_data$label <- as.factor(subset_data$label)
  condpost_pre <- c(-1, 1)
  contrasts(subset_data$label) <- cbind(condpost_pre)
  
  # Fit the LME!
  model3 <- lmer(1 - r ~ label + (1 | sub), data = subset_data)
  
  # Check for singularity
  if (isSingular(model3, tol = 1e-4)) {
    # If a singularity warning, increment the counter!
    singularity_count <- singularity_count + 1
    singular_nodes <- c(singular_nodes, node)
    model_summary <- summary(model3)
    
    # Extract the estimate and p-value for the label contrast
    estimate <- model_summary$coefficients["labelcondpost_pre", "Estimate"]
    p_value <- model_summary$coefficients["labelcondpost_pre", "Pr(>|t|)"]
    
    result_df <- rbind(result_df, data.frame(node = node, estimate = estimate, p = p_value))
  } else {
    model_summary <- summary(model3)
    
    estimate <- model_summary$coefficients["labelcondpost_pre", "Estimate"]
    p_value <- model_summary$coefficients["labelcondpost_pre", "Pr(>|t|)"]
    
    result_df <- rbind(result_df, data.frame(node = node, estimate = estimate, p = p_value))
  }
}

print(paste("Number of nodes with singularity error:", singularity_count))


output_folder <- "model_outputs"
if (!file.exists(output_folder)) {
  dir.create(output_folder)
}
output_file <- file.path(output_folder, "lmer_across_node_estimate_pre_post_twist_new.csv")
write.csv(result_df, file = output_file, row.names = FALSE)

```
