---
title: "madlibs_iteration9_memory_analyses"
output: html_document
date: '2023-04-21'
---


```{r, include=FALSE}
library(lme4)
library(lmerTest)
library(sjPlot)
```


## DATA
```{r}
data = read.csv('1.6._pretwist_posttwist_matched_length_median_segments_subcortical_new.csv')

dim(data)
```



### setting up the data frames
```{r}
data$label <- as.factor(data$Label)
condpost_pre <- c(-1,1)   #will set up the model as a distance 
contrasts(data$label) <- cbind(condpost_pre)
```


## Do it per node:
```{r}
unique_iterations <- unique(data$Iteration)
unique_nodes <- unique(data$Node)

output_folder <- "model_outputs"

if (!file.exists(output_folder)) {
  dir.create(output_folder)
}

# Loop through each iteration
for (iteration in unique_iterations) {
  
  # Initialize result data frame for the current iteration
  result_df <- data.frame(Subject = character(), Node = numeric(), Estimate = numeric(), P_Value = numeric(), stringsAsFactors = FALSE)
  
  # Filter the data for the current iteration
  iteration_data <- subset(data, Iteration == iteration)
  
  # Loop through each node
  for (node in unique_nodes) {
    
    print(paste("Iteration:", iteration, "Node:", node))
    
    subset_data <- subset(iteration_data, Node == node)
    subset_data$Label <- as.factor(subset_data$Label)
    contrasts(subset_data$Label) <- cbind(c(-1, 1))  # Set up the model as a distance
    
    # Fit the mixed-effects model
    model <- lmer(1 - Median_R_Value ~ Label + (1 | Subject), data = subset_data)
    
    # Get the model summary
    model_summary <- summary(model)
    
    # Extract the estimate and p-value for the condition
    estimate <- model_summary$coefficients["Label1", "Estimate"]
    p_value <- model_summary$coefficients["Label1", "Pr(>|t|)"]
    
    # Add the results to the data frame
    result_df <- rbind(result_df, data.frame(Node = node, Estimate = estimate, P_Value = p_value))
  }
  
  # Define the file path for saving the result data frame
  output_file <- file.path(output_folder, paste0("lmer_results_compare_segments_matched_length_iteration_nuisanceCRM_subcortical", iteration, ".csv"))
  
  
  # Save the result data frame to a CSV file in the sub-folder
  write.csv(result_df, file = output_file, row.names = FALSE)
}


```

